on: 
  push:
defaults:
  run:
    shell: bash

jobs:
  react-native:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4  
    - name: Set up Java
      uses: actions/setup-java@v2
      with:
        java-version: 17
        distribution: 'zulu' 

    - name: Init
      run: |
        npm install
        npm install -g appcenter-cli

    - name: build
      run: |
        cd android
        chmod +x gradlew
        ./gradlew build
        find . -name '*.apk'

    # - name: Verificar ruta del APK
    #   run: echo 'La ruta del APK es: $GITHUB_WORKSPACE/android/app/build/outputs/apk/debug/app-debug.apk'

    - name: deploy
      run: | 
        cd android
        appcenter distribute release
          --app KevindelCid/rnBase
          --file app/build/outputs/apk/debug/app-debug.apk
          --group "Collaborators"
          --token ${{ secrets.APP_CENTER_TOKEN }}

