on:
  push:
jobs:
  react-native:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Java
        uses: actions/setup-java@v2
        with:
          java-version: 17
          distribution: 'zulu'
      - name: Install dependencies
        run: |
          npm install
          npm install -g appcenter-cli
      - name: Build APK
        run: |
          cd android
          chmod +x gradlew
          ./gradlew build
          find . -name '*.apk'
      - name: Deploy to App Center
        run: |
          cd android
          sed -i 's/CHANGE_ME/"5955c427-d449-4e32-a6dc-c0af4bbc1096"/g' app/src/assets/appcenter-config.json
          appcenter distribute release \
            --app KevindelCid/rnBase \
            --file app/build/outputs/apk/debug/app-debug.apk \
            --group "Collaborators" \
            --token "5955c427-d449-4e32-a6dc-c0af4bbc1096"