on:
  push:
jobs:
  react-native:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Java
        uses: actions/setup-java@v2
        with:
          java-version: 17
          distribution: 'zulu'
      - name: Install dependencies
        run: |
          npm install
          npm install -g appcenter-cli
      - name: Build APK
        run: |
          cd android
          chmod +x gradlew
          ./gradlew build
          find . -name '*.apk'
      - name: Deploy to App Center
        run: |
          cd android
          appcenter distribute release \
            --app KevindelCid/rnBase \
            --file app/build/outputs/apk/debug/app-debug.apk \
            --group "Collaborators" \
            --token ${{ secrets.APP_CENTER_TOKEN }}